//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkInspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current version of the application..
        /// </summary>
        internal static string GetHelpCommandDescription {
            get {
                return ResourceManager.GetString("GetHelpCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: LinkInspector.exe -u &quot;&lt;URL&gt;&quot; [options].
        /// </summary>
        internal static string GetHelpRunUsage {
            get {
                return ResourceManager.GetString("GetHelpRunUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        internal static string GetVerionRunCurrentVersion {
            get {
                return ResourceManager.GetString("GetVerionRunCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current version of the application..
        /// </summary>
        internal static string GetVersionRunCurrentVersionInfo {
            get {
                return ResourceManager.GetString("GetVersionRunCurrentVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create Uri from the string specified: &apos;{0}&apos;.
        /// </summary>
        internal static string ParseUrlRunCantCreateUriError {
            get {
                return ResourceManager.GetString("ParseUrlRunCantCreateUriError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input argument &apos;{0}&apos; is not an integer value and must be greater than 0..
        /// </summary>
        internal static string ParseUrlRunNotIntegerError {
            get {
                return ResourceManager.GetString("ParseUrlRunNotIntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format {0}.
        /// </summary>
        internal static string ParseUrlRunUnsupportedFormatError {
            get {
                return ResourceManager.GetString("ParseUrlRunUnsupportedFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file could not be read:.
        /// </summary>
        internal static string ReportGetFileContentCantReadError {
            get {
                return ResourceManager.GetString("ReportGetFileContentCantReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4}/{1,-4}: .
        /// </summary>
        internal static string WebSpiderExecuteProcessedUrlsInfo {
            get {
                return ResourceManager.GetString("WebSpiderExecuteProcessedUrlsInfo", resourceCulture);
            }
        }
    }
}
